### ISSUE TITLE
`HE_SPRITE_MODULE` define could be optional

### ISSUE THREAD

**Issue by boozook** [risolvipro/HEBitmap#3]
Please remove [this line](https://github.com/risolvipro/HEBitmap/blob/main/src/he_api.h#L11) `#define HE_SPRITE_MODULE` to make it optional. Currently I can't build without sprite- symbols, but could be great.

So I can define it in cmake or just directly telling to compiler.

Same for entire Lua-part, but there is more complex thing,

**Comment by risolvipro** [comment]
Added `#define HE_SPRITE_MODULE 1` in `he_api.h`, you can also set it from the compiler.

**Comment by boozook** [comment]
Thank you ❤️‍🔥
