### ISSUE TITLE
Redefinable `HE_GFX_STACK_SIZE`

### ISSUE THREAD

**Issue by boozook** [risolvipro/HEBitmap#5]
Please allow to redefine `HE_GFX_STACK_SIZE`. Currently it's [just defined](https://github.com/risolvipro/HEBitmap/blob/main/src/he_api.c#L13). Could be great to define it _only if_ it isn't defined yet. Like this:
```c
#ifndef HE_GFX_STACK_SIZE
#define HE_GFX_STACK_SIZE 1024
#endif
```

**Comment by risolvipro** [comment]
I'll work on it soon, thanks for the feedback.

**Comment by risolvipro** [comment]
Added in the latest commit 👍

**Comment by boozook** [comment]
Thank you 😊
